import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        firebase: 'readonly',
        navigator: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        URL: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        clients: 'readonly',
        location: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        Notification: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        importScripts: 'readonly',
        updatePendingDevicesBadge: 'readonly',
        isAdmin: 'writable',
        currentUser: 'writable',
        localTodayStr: 'readonly',
        getLocalDateTimeString: 'readonly',
        db: 'readonly',
        i18n: 'readonly',
        currentLang: 'readonly',
        PinThipSafe: 'readonly',
        setStatusText: 'readonly',
        safeText: 'readonly',
        showNotificationSoundControl: 'readonly',
        enableNotificationSound: 'readonly',
        startDevicePresence: 'readonly',
        startDeviceAccessGuard: 'readonly',
        stopDevicePresence: 'readonly',
        stopDeviceAccessGuard: 'readonly',
        checkCurrentDeviceAccess: 'readonly',
        showAdminDashboard: 'readonly',
        startAdminNotificationListener: 'readonly',
        stopAdminNotificationListener: 'readonly',
        stopTodayListRealtime: 'readonly',
        isCustomAuthEnabled: 'readonly',
        checkDeviceAccess: 'readonly',
        showDashboard: 'readonly',
        showLoginForm: 'readonly',
        handleLogin: 'readonly',
        handleLogout: 'readonly',
        validateUsernameLength: 'readonly',
        showNotification: 'readonly',
        showModal: 'readonly',
        closeModal: 'readonly',
        openWideModal: 'readonly',
        getDeviceInfo: 'readonly',
        showFoamAdminView: 'readonly',
        showPrintLayoutEditor: 'readonly',
        showAdminNotificationModal: 'readonly',
        showNotificationModal: 'readonly',
        initPushNotifications: 'readonly',
        initApp: 'readonly',
        playNotificationAlert: 'readonly',
        showDesktopNotification: 'readonly',
        toggleDrawer: 'readonly',
        setLanguage: 'readonly',
        toggleNotificationSound: 'readonly',
        recoverFirebaseSession: 'readonly',
        resetExpiredAuthSession: 'readonly',
        requireFirebaseAuth: 'readonly',
        downloadCSV: 'readonly',
        calculateDistance: 'readonly'
      }
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-useless-escape': 'off'
    }
  }
];